<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace>WSM.App.Modern</RootNamespace>
    <AssemblyName>WSM</AssemblyName>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WSM.App.Shared\WSM.App.Shared.csproj" />
    <ProjectReference Include="..\WSM.Infrastructure\WSM.Infrastructure.csproj" />
  </ItemGroup>

</Project>
